spring:
  application:
    name: spring-kafka-demo
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cloud:
    function:
      definition: process;consumeOnly
    stream:
      default:
        content-type: application/json
      kafka:
        binder:
          brokers: localhost:29092
          auto-create-topics: true
          auto-create-topics-partitions: 1
          auto-create-topics-replication-factor: 1
      bindings:
        process-in-0:
          destination: input
          group: process-group-1
          content-type: application/json
        consumeOnly-in-0:
          destination: input
          group: consume-only-group-1
          content-type: application/json
        process-out-0:
          destination: output
          content-type: application/json
          producer:
            useNativeEncoding: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: demo
      username: admin
      password: password
      authentication-database: admin