spring:
  application:
    name: spring-kafka-demo
  kafka:
    handler:
      internal-topic: process
      response-topic: response
      error-topic: error
    bootstrap-servers: localhost:29092
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cloud:
    function:
      definition: consumeAndProduce;consumeOnly;process
    stream:
      default:
        content-type: application/json
      kafka:
        binder:
          brokers: localhost:29092
          auto-create-topics: true
          auto-create-topics-partitions: 1
          auto-create-topics-replication-factor: 1
      bindings:
        process-in-0:
          destination: ${spring.kafka.handler.internal-topic}
          group: process-group-1
          content-type: application/json
        consumeOnly-in-0:
          destination: example-input
          group: consume-only-group-1
          content-type: application/json
        consumeAndProduce-in-0:
          destination: example-input
          group: consume-produce-group-1
          content-type: application/json
        consumeAndProduce-out-0:
          destination: example-output
          content-type: application/json
          producer:
            useNativeEncoding: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: demo
      username: admin
      password: password
      authentication-database: admin